### ISSUE TITLE
3天前建立的仓库，感觉是有人利用这个仓库人为做空。

### ISSUE THREAD

**Issue by baiban1993** [ShowCoin/ShowCoin#19]
以太坊合约的代码，只有写完了才能发代币……没有代码的话，根本都没法发币。

**Comment by lucunlu** [comment]
我是从官网的github链接点过来的.官网(http://www.show.one/)链接最下面，有github。看到新闻才知道这个项目........

**Comment by baiban1993** [comment]
嗯，看了看的确是官方的。但是很明显这也是人为做空，有人拿这个github做文章。

**Comment by lucunlu** [comment]
不谈做不做空。就这样一个不负责任的github，我真的不知道说什么......我只想说，真的厉害.....

**Comment by merrynode** [comment]
我建议你去看看别人ICO之前的代码库，基本上代码都有进展了，SHOW是ICO结束了，代码提交了一个Hello world.

**Comment by lucunlu** [comment]
具体代码库，我不清楚，我是从看新闻从官网点过来的....被骚气到了

**Comment by baiban1993** [comment]
@merrynode  这么说的话，我也真没话说。毕竟也没有规定，ICO结束之前必须把项目做到哪一步。人家也有自己的开发计划。看好就持仓，不看好就走人。我觉得喷的有点不对劲。
